export const en = {
  'app.title': 'Support Desk', 'nav.main': 'Main navigation', 'nav.tickets': 'Tickets', 'nav.projects': 'Projects', 'nav.categories': 'Categories', 'nav.dashboard': 'Dashboard', 'nav.reports': 'Reports', 'nav.profile': 'Profile', 'nav.administration': 'Administration', 'account.logout': 'Log out', 'language.label': 'Language', 'language.english': 'English', 'language.spanish': 'Español',
  'login.title': 'Sign in', 'login.subtitle': 'Access your support workspace.', 'login.email': 'Email', 'login.password': 'Password', 'login.emailError': 'Enter a valid email address.', 'login.passwordError': 'Password is required.', 'login.signingIn': 'Signing in…', 'login.signIn': 'Sign in', 'login.defaultError': 'Unable to sign in. Check your email and password.',
  'common.edit': 'Edit', 'common.new': 'New', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.saving': 'Saving…', 'common.delete': 'Delete', 'common.name': 'Name', 'common.description': 'Description', 'common.actions': 'Actions', 'common.all': 'All', 'common.project': 'Project', 'common.category': 'Category', 'common.priority': 'Priority', 'common.status': 'Status', 'common.kind': 'Kind', 'common.keyword': 'Keyword', 'common.from': 'From', 'common.to': 'To',
  'ticket.edit': 'Edit ticket', 'ticket.new': 'New ticket', 'ticket.title': 'Title', 'ticket.titleError': 'A title is required (255 characters maximum).', 'ticket.assignee': 'Assignee', 'ticket.noProject': 'No project', 'ticket.noCategory': 'No category', 'ticket.unassigned': 'Unassigned', 'ticket.save': 'Save ticket', 'ticket.searchHelp': 'Search and manage support work.', 'ticket.newAction': 'New ticket', 'ticket.placeholder': 'Title or description', 'ticket.allProjects': 'All projects', 'ticket.allCategories': 'All categories', 'ticket.applyFilters': 'Apply filters', 'ticket.assigneeColumn': 'Assignee', 'ticket.created': 'Created', 'ticket.none': 'No tickets match.',
  'project.edit': 'Edit project', 'project.new': 'New project', 'project.nameError': 'Enter a project name up to 150 characters.', 'project.save': 'Save project', 'project.organize': 'Organize tickets by project.', 'project.newAction': 'New project', 'project.tickets': 'Tickets', 'project.pending': 'Pending', 'project.none': 'No projects yet.',
  'user.manageHelp': 'Manage user accounts and access.', 'user.newAction': 'New user', 'user.new': 'New user', 'user.edit': 'Edit user', 'user.name': 'Name', 'user.email': 'Email', 'user.firstName': 'First name', 'user.lastName': 'Last name', 'user.role': 'Role', 'user.status': 'Account status', 'user.active': 'Active', 'user.inactive': 'Inactive', 'user.roleAdmin': 'Admin', 'user.roleUser': 'User', 'user.password': 'Password', 'user.passwordHint': 'Use at least 8 characters.', 'user.passwordOptional': 'Leave blank to keep the current password.', 'user.passwordError': 'Password must be at least 8 characters.', 'user.emailError': 'Enter a valid email address.', 'user.requiredError': 'This field is required.', 'user.save': 'Save user', 'user.none': 'No users found.', 'user.deleteConfirm': 'Delete user “{name}”?', 'user.loadError': 'Unable to load users.', 'user.loadOneError': 'Unable to load user.', 'user.deleteError': 'Unable to delete user. The account may be protected or in use.', 'user.saveError': 'Unable to save user. Check the fields and whether the email is already in use.',
  'category.edit': 'Edit category', 'category.new': 'New category', 'category.nameError': 'A category name is required (150 characters maximum).', 'category.save': 'Save category', 'category.classify': 'Classify support tickets.', 'category.newAction': 'New category', 'category.none': 'No categories yet.',
  'dashboard.pending': 'Pending tickets', 'dashboard.byStatus': 'By status', 'dashboard.byProject': 'By project', 'dashboard.byCategory': 'By category', 'dashboard.noTickets': 'No ticket data.', 'dashboard.noProjects': 'No projects with tickets.', 'dashboard.noCategories': 'No categories with tickets.',
  'dashboard.eyebrow': 'Support overview', 'dashboard.title': 'Dashboard', 'dashboard.totalTickets': 'Total tickets', 'dashboard.clientReplies': 'Client replies', 'dashboard.staffReplies': 'Staff replies', 'dashboard.ticketsWithoutReply': 'Tickets without reply', 'dashboard.replyActivity': 'Reply activity', 'dashboard.last14Days': 'Daily replies · last 14 days', 'dashboard.repliesToday': 'replies today', 'dashboard.priorityBreakdown': 'Priority breakdown', 'dashboard.activeTickets': 'Active tickets', 'dashboard.active': 'Active', 'dashboard.noPriorityData': 'No active tickets.', 'dashboard.ticketTrend': 'Tickets created vs. solved', 'dashboard.last7Days': 'Daily activity · last 7 days', 'dashboard.viewReport': 'View report', 'dashboard.created': 'Created', 'dashboard.solved': 'Solved', 'dashboard.noTrendData': 'No ticket activity yet.', 'dashboard.recentTickets': 'Recent tickets', 'dashboard.latestWork': 'Latest support activity', 'dashboard.viewAll': 'View all', 'dashboard.noRecentTickets': 'No tickets yet.',
  'reports.title': 'Ticket reports', 'reports.generate': 'Generate', 'reports.matching': 'matching tickets', 'reports.none': 'No matching tickets.',
  'profile.title': 'My profile', 'profile.role': 'Role', 'profile.active': 'Active', 'profile.inactive': 'Inactive', 'profile.changePassword': 'Change password', 'profile.currentPassword': 'Current password', 'profile.newPassword': 'New password', 'profile.passwordHint': 'Use at least 8 characters.',
  'value.ticket': 'Ticket', 'value.bug': 'Bug', 'value.suggestion': 'Suggestion', 'value.feature': 'Feature', 'value.high': 'High', 'value.medium': 'Medium', 'value.low': 'Low', 'value.pending': 'Pending', 'value.in_progress': 'In progress', 'value.done': 'Done', 'value.cancelled': 'Cancelled',
  'dashboard.loadError': 'Unable to load dashboard.', 'reports.generateError': 'Unable to generate report.', 'profile.loadError': 'Unable to load your profile.', 'profile.passwordSuccess': 'Password changed successfully.', 'profile.passwordError': 'Unable to change password. Check your current password.', 'project.loadError': 'Unable to load projects.', 'project.deleteError': 'Unable to delete project. Admin access may be required.', 'project.loadOneError': 'Unable to load project.', 'project.saveError': 'Unable to save project.', 'category.loadError': 'Unable to load categories.', 'category.deleteError': 'Unable to delete category. Admin access may be required.', 'category.loadOneError': 'Unable to load category.', 'category.saveError': 'Unable to save category. The name may already exist.', 'ticket.assigneesError': 'Unable to load assignees. Admin access may be required.', 'ticket.loadError': 'Unable to load ticket.', 'ticket.saveError': 'Unable to save ticket. Check the fields and your assignee access.', 'ticket.listLoadError': 'Unable to load tickets.', 'ticket.deleteError': 'Unable to delete ticket.'
} as const;

export type TranslationKey = keyof typeof en;
