import { en, TranslationKey } from './en';

export const es: Record<TranslationKey, string> = {
  'app.title': 'Mesa de soporte', 'nav.main': 'Navegación principal', 'nav.tickets': 'Tickets', 'nav.projects': 'Proyectos', 'nav.categories': 'Categorías', 'nav.dashboard': 'Panel', 'nav.reports': 'Informes', 'nav.profile': 'Perfil', 'nav.administration': 'Administración', 'account.logout': 'Cerrar sesión', 'language.label': 'Idioma', 'language.english': 'English', 'language.spanish': 'Español',
  'login.title': 'Iniciar sesión', 'login.subtitle': 'Accede a tu espacio de soporte.', 'login.email': 'Correo electrónico', 'login.password': 'Contraseña', 'login.emailError': 'Introduce un correo electrónico válido.', 'login.passwordError': 'La contraseña es obligatoria.', 'login.signingIn': 'Iniciando sesión…', 'login.signIn': 'Iniciar sesión', 'login.defaultError': 'No se pudo iniciar sesión. Revisa tu correo y contraseña.',
  'common.edit': 'Editar', 'common.new': 'Nuevo', 'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.saving': 'Guardando…', 'common.delete': 'Eliminar', 'common.name': 'Nombre', 'common.description': 'Descripción', 'common.actions': 'Acciones', 'common.all': 'Todos', 'common.project': 'Proyecto', 'common.category': 'Categoría', 'common.priority': 'Prioridad', 'common.status': 'Estado', 'common.kind': 'Tipo', 'common.keyword': 'Palabra clave', 'common.from': 'Desde', 'common.to': 'Hasta',
  'ticket.edit': 'Editar ticket', 'ticket.new': 'Nuevo ticket', 'ticket.title': 'Título', 'ticket.titleError': 'El título es obligatorio (máximo 255 caracteres).', 'ticket.assignee': 'Responsable', 'ticket.noProject': 'Sin proyecto', 'ticket.noCategory': 'Sin categoría', 'ticket.unassigned': 'Sin asignar', 'ticket.save': 'Guardar ticket', 'ticket.searchHelp': 'Busca y administra el trabajo de soporte.', 'ticket.newAction': 'Nuevo ticket', 'ticket.placeholder': 'Título o descripción', 'ticket.allProjects': 'Todos los proyectos', 'ticket.allCategories': 'Todas las categorías', 'ticket.applyFilters': 'Aplicar filtros', 'ticket.assigneeColumn': 'Responsable', 'ticket.created': 'Creado', 'ticket.none': 'No hay tickets que coincidan.', 'ticket.reportedBy': 'Reportado por', 'ticket.publicSubmission': 'Solicitud pública', 'ticket.reporterName': 'Nombre', 'ticket.reporterEmail': 'Correo electrónico', 'ticket.reporterLocation': 'Ubicación',
  'project.edit': 'Editar proyecto', 'project.new': 'Nuevo proyecto', 'project.nameError': 'Introduce un nombre de proyecto de hasta 150 caracteres.', 'project.webhookUrl': 'URL del webhook (opcional)', 'project.webhookUrlError': 'Introduce una URL válida que comience con http:// o https://.', 'project.save': 'Guardar proyecto', 'project.organize': 'Organiza tickets por proyecto.', 'project.newAction': 'Nuevo proyecto', 'project.tickets': 'Tickets', 'project.pending': 'Pendientes', 'project.none': 'Aún no hay proyectos.',
  'publicTicket.loading': 'Cargando proyecto…', 'publicTicket.unavailableTitle': 'Formulario no disponible', 'publicTicket.projectLoadError': 'El enlace del proyecto no es válido o ya no está disponible.', 'publicTicket.title': 'Enviar una solicitud de soporte', 'publicTicket.projectLabel': 'Proyecto', 'publicTicket.reporterName': 'Tu nombre', 'publicTicket.reporterEmail': 'Tu correo electrónico', 'publicTicket.reporterLocation': 'Tu ubicación (opcional)', 'publicTicket.emailNotifications': 'Envíenme un correo cuando se actualice este ticket', 'publicTicket.successTitle': 'Solicitud enviada', 'publicTicket.successMessage': 'Tu solicitud de soporte se envió correctamente.', 'publicTicket.submit': 'Enviar solicitud', 'publicTicket.submitting': 'Enviando…', 'publicTicket.submitError': 'No se pudo enviar la solicitud. Inténtalo de nuevo.', 'publicTicket.requiredError': 'Este campo es obligatorio.', 'publicTicket.emailError': 'Introduce un correo electrónico válido.', 'publicTicket.fieldTooLong': 'Este campo es demasiado largo.',
  'user.manageHelp': 'Administra las cuentas y el acceso de usuarios.', 'user.newAction': 'Nuevo usuario', 'user.new': 'Nuevo usuario', 'user.edit': 'Editar usuario', 'user.name': 'Nombre', 'user.email': 'Correo electrónico', 'user.firstName': 'Nombre', 'user.lastName': 'Apellidos', 'user.role': 'Rol', 'user.status': 'Estado de la cuenta', 'user.active': 'Activo', 'user.inactive': 'Inactivo', 'user.roleAdmin': 'Administrador', 'user.roleUser': 'Usuario', 'user.password': 'Contraseña', 'user.passwordHint': 'Usa al menos 8 caracteres.', 'user.passwordOptional': 'Déjalo en blanco para conservar la contraseña actual.', 'user.passwordError': 'La contraseña debe tener al menos 8 caracteres.', 'user.emailError': 'Introduce un correo electrónico válido.', 'user.requiredError': 'Este campo es obligatorio.', 'user.save': 'Guardar usuario', 'user.none': 'No se encontraron usuarios.', 'user.deleteConfirm': '¿Eliminar al usuario «{name}»?', 'user.loadError': 'No se pudieron cargar los usuarios.', 'user.loadOneError': 'No se pudo cargar el usuario.', 'user.deleteError': 'No se pudo eliminar el usuario. La cuenta puede estar protegida o en uso.', 'user.saveError': 'No se pudo guardar el usuario. Revisa los campos y si el correo ya está en uso.',
  'category.edit': 'Editar categoría', 'category.new': 'Nueva categoría', 'category.nameError': 'El nombre de categoría es obligatorio (máximo 150 caracteres).', 'category.save': 'Guardar categoría', 'category.classify': 'Clasifica los tickets de soporte.', 'category.newAction': 'Nueva categoría', 'category.none': 'Aún no hay categorías.',
  'dashboard.pending': 'Tickets pendientes', 'dashboard.byStatus': 'Por estado', 'dashboard.byProject': 'Por proyecto', 'dashboard.byCategory': 'Por categoría', 'dashboard.noTickets': 'No hay datos de tickets.', 'dashboard.noProjects': 'No hay proyectos con tickets.', 'dashboard.noCategories': 'No hay categorías con tickets.',
  'dashboard.eyebrow': 'Resumen de soporte', 'dashboard.title': 'Panel', 'dashboard.totalTickets': 'Tickets totales', 'dashboard.clientReplies': 'Respuestas del cliente', 'dashboard.staffReplies': 'Respuestas del equipo', 'dashboard.ticketsWithoutReply': 'Tickets sin respuesta', 'dashboard.replyActivity': 'Actividad de respuestas', 'dashboard.last14Days': 'Respuestas diarias · últimos 14 días', 'dashboard.repliesToday': 'respuestas hoy', 'dashboard.priorityBreakdown': 'Tickets por prioridad', 'dashboard.activeTickets': 'Tickets activos', 'dashboard.active': 'Activos', 'dashboard.noPriorityData': 'No hay tickets activos.', 'dashboard.ticketTrend': 'Tickets creados y resueltos', 'dashboard.last7Days': 'Actividad diaria · últimos 7 días', 'dashboard.viewReport': 'Ver informe', 'dashboard.created': 'Creados', 'dashboard.solved': 'Resueltos', 'dashboard.noTrendData': 'Aún no hay actividad de tickets.', 'dashboard.recentTickets': 'Tickets recientes', 'dashboard.latestWork': 'Actividad de soporte reciente', 'dashboard.viewAll': 'Ver todos', 'dashboard.noRecentTickets': 'Aún no hay tickets.',
  'reports.title': 'Informes de tickets', 'reports.generate': 'Generar', 'reports.matching': 'tickets coincidentes', 'reports.none': 'No hay tickets coincidentes.',
  'profile.title': 'Mi perfil', 'profile.role': 'Rol', 'profile.active': 'Activo', 'profile.inactive': 'Inactivo', 'profile.changePassword': 'Cambiar contraseña', 'profile.currentPassword': 'Contraseña actual', 'profile.newPassword': 'Nueva contraseña', 'profile.passwordHint': 'Usa al menos 8 caracteres.',
  'value.ticket': 'Ticket', 'value.bug': 'Error', 'value.suggestion': 'Sugerencia', 'value.feature': 'Funcionalidad', 'value.high': 'Alta', 'value.medium': 'Media', 'value.low': 'Baja', 'value.pending': 'Pendiente', 'value.in_progress': 'En progreso', 'value.done': 'Completado', 'value.cancelled': 'Cancelado',
  'dashboard.loadError': 'No se pudo cargar el panel.', 'reports.generateError': 'No se pudo generar el informe.', 'profile.loadError': 'No se pudo cargar tu perfil.', 'profile.passwordSuccess': 'La contraseña se cambió correctamente.', 'profile.passwordError': 'No se pudo cambiar la contraseña. Revisa tu contraseña actual.', 'project.loadError': 'No se pudieron cargar los proyectos.', 'project.deleteError': 'No se pudo eliminar el proyecto. Puede que necesites acceso de administrador.', 'project.loadOneError': 'No se pudo cargar el proyecto.', 'project.saveError': 'No se pudo guardar el proyecto.', 'category.loadError': 'No se pudieron cargar las categorías.', 'category.deleteError': 'No se pudo eliminar la categoría. Puede que necesites acceso de administrador.', 'category.loadOneError': 'No se pudo cargar la categoría.', 'category.saveError': 'No se pudo guardar la categoría. Es posible que el nombre ya exista.', 'ticket.assigneesError': 'No se pudieron cargar los responsables. Es posible que necesites acceso de administrador.', 'ticket.loadError': 'No se pudo cargar el ticket.', 'ticket.saveError': 'No se pudo guardar el ticket. Revisa los campos y el acceso al responsable.', 'ticket.listLoadError': 'No se pudieron cargar los tickets.', 'ticket.deleteError': 'No se pudo eliminar el ticket.'
};
